# Generated by Django 4.1.5 on 2023-01-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=40)),
                ('date_of_creation', models.DateField(auto_now=True)),
                ('negotiable', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.realestateagent')),
            ],
        ),
    ]
