# Generated by Django 4.1.5 on 2023-01-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realestatead',
            options={'managed': 'false'},
        ),
        migrations.AlterModelTable(
            name='realestatead',
            table='real_estate_ad',
        ),
    ]
